language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-pd-project' ]; then cd .. && eval "mv $currentfolder generator-pd-project" && cd generator-pd-project; fi

